version: "3"
services:

  web:
    container_name: myweb
    depends_on:
      - redis
      - mysql
    build: "."
    ports:
      - "127.0.0.1:3030:3030"
    links:
      - redis
      - mysql

  mysql:
    container_name: mymysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    container_name: myredis
    image: redis:latest
    ports:
      - "6379:6379"
    restart:
      always

